apiVersion: v2
name: lemonade-stand-assistant
description: A Helm chart for Lemonade Stand Assistant Application
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: sarabanderby
  - name: ckavili
