---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: guardrails-detector-runtime-language-detector
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--workers'
        - '4'
        - '--host'
        - 0.0.0.0
        - '--port'
        - '8000'
        - '--log-config'
        - /common/log_conf.yaml
      command:
        - uvicorn
        - 'app:app'
      env:
        - name: MODEL_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: SAFE_LABELS
          value: '["en","tr"]'
      image: 'quay.io/rh-ee-mmisiura/hf-detector:latest'
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: guardrails-detector-huggingface
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: language-detector
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: language-detector
  finalizers:
    - odh.inferenceservice.finalizers
    - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: guardrails-detector-huggingface
      name: ''
      resources:
        limits:
          cpu: '1'
          memory: 12Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '1'
          memory: 6Gi
          nvidia.com/gpu: '1'
      runtime: guardrails-detector-runtime-language-detector
      storage:
        key: aws-connection-minio-data-connection-detector-models
        path: xlm-roberta-base-language-detection
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: Tesla-T4-SHARED
